plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace "com.practicum.mymovies"
    compileSdk 34

    defaultConfig {
        applicationId "com.practicum.mymovies"
        minSdk 28
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles(
                    getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    viewBinding {
        enabled = true
    }
}

dependencies {
    def moxyVersion = '2.2.2'

    implementation libs.moxy
    implementation libs.moxy.android
    kapt "com.github.moxy-community:moxy-compiler:$moxyVersion"

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.glide
    implementation libs.gson
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.viewpager2
    implementation libs.koin.android
    implementation libs.adapterdelegates4.kotlin.dsl
    implementation libs.adapterdelegates4.kotlin.dsl.viewbinding
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    implementation libs.kotlinx.coroutines.android
}

